# espanso configuration file

backend: Inject
auto_restart: true
fast_inject: true

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/